# Generated by Django 6.0.4 on 2026-04-30 09:13

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("news", "0001_initial"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="artikel",
            name="penulis",
        ),
        migrations.AlterField(
            model_name="artikel",
            name="gambar_cover",
            field=models.ImageField(blank=True, null=True, upload_to="berita/"),
        ),
        migrations.CreateModel(
            name="Komentar",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("nama_pengguna", models.CharField(max_length=100)),
                ("isi_komentar", models.TextField()),
                ("tanggal_dibuat", models.DateTimeField(auto_now_add=True)),
                (
                    "artikel",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="komentar",
                        to="news.artikel",
                    ),
                ),
            ],
        ),
    ]
