# Generated by Django 6.0.4 on 2026-05-03 06:41

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("news", "0002_remove_artikel_penulis_alter_artikel_gambar_cover_and_more"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RenameField(
            model_name="artikel",
            old_name="konten",
            new_name="isi",
        ),
        migrations.AddField(
            model_name="artikel",
            name="penulis",
            field=models.ForeignKey(
                default=1,
                on_delete=django.db.models.deletion.CASCADE,
                to=settings.AUTH_USER_MODEL,
            ),
            preserve_default=False,
        ),
    ]
