# Generated by Django 6.0.4 on 2026-06-17 16:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("news", "0004_alter_artikel_penulis"),
    ]

    operations = [
        migrations.AddField(
            model_name="artikel",
            name="jumlah_views",
            field=models.PositiveIntegerField(default=0),
        ),
    ]
